import { create } from "zustand";

const useHotelStore = create((set) => ({
  hotels: [
    {
      id: 1,
      name: "The Strand Hotel",
      slug: "the-strand-hotel",
      location: "Yangon",
      description:
        "I recently stayed at The Stand Hotel , and it was hands down the best vacation of my life. The room was luxurious, with a glass floor to view marine life and a private plunge pool. It features opulent rooms, fine dining, and state-of-the-art amenities, quickly becoming one of Yangon's most prestigious stays.​",
      images: [
        "/src/assets/hotel-assets/1.The Stand Hotel/Hotels_The Stand Hotel_1.png",
        "/src/assets/hotel-assets/1.The Stand Hotel/Hotels_The Stand Hotel_2.png",
        "/src/assets/hotel-assets/1.The Stand Hotel/Hotels_The Stand Hotel_3.png",
        "/src/assets/hotel-assets/1.The Stand Hotel/Hotels_The Stand Hotel_4.png",
      ],
      reviews: 4321,
      rating: 4.3,
      buttonText: "Check Availability",
    },
    {
      id: 2,
      name: "Eastern Palace Hotel",
      slug: "eastern-palace-hotel",
      location: "Mandalay",
      description:
        "The hotel’s restaurant served a great breakfast with plenty of healthy options. The staff were attentive and quick to resolve a minor issue I had with my room key. While the hotel doesn’t have the extravagant touches of a 5-star property, it delivers everything you’d expect from a solid 4-star experience. Great for business travelers!",
      images: [
        "/src/assets/hotel-assets/2.Eastern Palace Hotel/Hotels_Eastern Palace Hotel_1.png",
        "/src/assets/hotel-assets/2.Eastern Palace Hotel/Hotels_Eastern Palace Hotel_2.png",
        "/src/assets/hotel-assets/2.Eastern Palace Hotel/Hotels_Eastern Palace Hotel_3.png",
        "/src/assets/hotel-assets/2.Eastern Palace Hotel/Hotels_Eastern Palace Hotel_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 3,
      name: "Monte diVino Lodge",
      slug: "monte-divino-lodge",
      location: "Taunggyi",
      description:
        "The hotel’s location was fantastic, within walking distance of the Royal Mile and other attractions. The staff were approachable and happy to provide local recommendations. While the hotel doesn’t have extensive amenities like a spa, it’s a fantastic choice for a unique and comfortable stay.",
      images: [
        "/src/assets/hotel-assets/3.Monte diVino Lodge Hotel/Hotels_Monte_1.png",
        "/src/assets/hotel-assets/3.Monte diVino Lodge Hotel/Hotels_Monte_2.png",
        "/src/assets/hotel-assets/3.Monte diVino Lodge Hotel/Hotels_Monte_3.png",
        "/src/assets/hotel-assets/3.Monte diVino Lodge Hotel/Hotels_Monte_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 4,
      name: "Aureum Palace Hotel & Resort",
      slug: "aureum-palace-hotel",
      location: "Bagan",
      description:
        "Staying at The Gritti Palace in Venice was like stepping back in time. The hotel is a masterpiece of Burmese architecture, with opulent furnishings, Murano glass chandeliers, and historic artwork throughout. My room overlooked the Grand Canal, and the view was simply magical.",
      images: [
        "/src/assets/hotel-assets/4.Aureum Palace Hotel/Hotels_Aureum Palace_1.png",
        "/src/assets/hotel-assets/4.Aureum Palace Hotel/Hotels_Aureum Palace_2.png",
        "/src/assets/hotel-assets/4.Aureum Palace Hotel/Hotels_Aureum Palace_3.png",
        "/src/assets/hotel-assets/4.Aureum Palace Hotel/Hotels_Aureum Palace_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 5,
      name: "Lotte Hotel Yangon",
      slug: "lotte-hotel-yangon",
      location: "Yangon",
      description:
        "Staying at the Lotte Hotel Yangon in Yangon was like stepping into a world of timeless grandeur. My suite overlooked Central Park, offering breathtaking views that made waking up each morning a delight. The décor was opulent yet cozy, with luxurious touches like plush bedding, a marble bathroom, and bespoke toiletries.",
      images: [
        "/src/assets/hotel-assets/5.Lotte Yangon Hotel/Hotels_Lotte_1.png",
        "/src/assets/hotel-assets/5.Lotte Yangon Hotel/Hotels_Lotte_2.png",
        "/src/assets/hotel-assets/5.Lotte Yangon Hotel/Hotels_Lotte_3.png",
        "/src/assets/hotel-assets/5.Lotte Yangon Hotel/Hotels_Lotte_4.png",
      ],
      reviews: 4321,
      rating: 5,
      buttonText: "Check Availability",
    },
    {
      id: 6,
      name: "Triumph Hotel Mandalay",
      slug: "triumph-hotel-mandalay",
      location: "Mandalay",
      description:
        "Royal Taunggyi Hotel exceeded my expectations for a 4-star property. The room was spacious, with modern decor, an excellent mattress, and a large TV. The bathroom was spotless and stocked with quality toiletries.This hotel provides a perfect mix of natural beauty, mountain adventures, and vibrant local culture.",
      images: [
        "/src/assets/hotel-assets/6.Triumph Hotel/Hotels_Triumph Hotel_1.png",
        "/src/assets/hotel-assets/6.Triumph Hotel/Hotels_Triumph Hotel_2.png",
        "/src/assets/hotel-assets/6.Triumph Hotel/Hotels_Triumph Hotel_3.png",
        "/src/assets/hotel-assets/6.Triumph Hotel/Hotels_Triumph Hotel_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 7,
      name: "Inle Lake View Resort & Spa",
      slug: "inle-lake-view-resort",
      location: "Taunggyi",
      description:
        "The room was spacious and beautifully appointed with a blend of classic luxury and cutting-edge technology, including tablet controls for everything from lighting to room service.The hotel itself is incredibly spacious and well-appointed, with elegant rooms and excellent leisure facilities.",
      images: [
        "/src/assets/hotel-assets/7.Inle Lake Hotel/Hotels_Inle Lake_1.png",
        "/src/assets/hotel-assets/7.Inle Lake Hotel/Hotels_Inle Lake_2.png",
        "/src/assets/hotel-assets/7.Inle Lake Hotel/Hotels_Inle Lake_3.png",
        "/src/assets/hotel-assets/7.Inle Lake Hotel/Hotels_Inle Lake_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 8,
      name: "Heritage Bagan Hotel",
      slug: "heritage-bagan-hotel",
      location: "Bagan",
      description:
        "The Rosewood Beijing impressed me with its modern elegance and attention to detail. The room was beautifully designed, with floor-to-ceiling windows offering stunning city views. The luxurious bathroom featured a deep soaking tub and high-end toiletries.",
      images: [
        "/src/assets/hotel-assets/8.Heritage Bagan Hotel/Hotels_Heritage Bagan_1.png",
        "/src/assets/hotel-assets/8.Heritage Bagan Hotel/Hotels_Heritage Bagan_2.png",
        "/src/assets/hotel-assets/8.Heritage Bagan Hotel/Hotels_Heritage Bagan_3.png",
        "/src/assets/hotel-assets/8.Heritage Bagan Hotel/Hotels_Heritage Bagan_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 9,
      name: "NOVOTEL",
      slug: "novotel-yangon",
      location: "Yangon",
      description:
        "The service was impeccable—staff anticipated my needs before I even voiced them. Dining at their signature restaurant was a highlight, offering a fusion of Burmese and Western cuisines that were as much a feast for the eyes as the palate. NOVOTEL redefines urban luxury, and I can't wait to return.",
      images: [
        "/src/assets/hotel-assets/9.Novotal Hotel/Hotels_Novotal_1.png",
        "/src/assets/hotel-assets/9.Novotal Hotel/Hotels_Novotal_2.png",
        "/src/assets/hotel-assets/9.Novotal Hotel/Hotels_Novotal_3.png",
        "/src/assets/hotel-assets/9.Novotal Hotel/Hotels_Novotal_4.png",
      ],
      reviews: 4321,
      rating: 5,
      buttonText: "Check Availability",
    },
    {
      id: 10,
      name: "The Link 78 Mandalay Boutique Hotel",
      slug: "the-link-78-mandalay-boutique-hotel",
      location: "Mandalay",
      description:
        "The rooftop pool, while small, was a fantastic spot to relax after a day of exploring. The breakfast buffet had a good variety of local and international dishes, and the staff were friendly and helpful throughout my stay. A great value for its location and amenities!",
      images: [
        "/src/assets/hotel-assets/10.The Link 78 Hotel/Hotels_Link 78_1.png",
        "/src/assets/hotel-assets/10.The Link 78 Hotel/Hotels_Link 78_2.png",
        "/src/assets/hotel-assets/10.The Link 78 Hotel/Hotels_Link 78_3.png",
        "/src/assets/hotel-assets/10.The Link 78 Hotel/Hotels_Link 78_4.png",
      ],
      reviews: 4321,
      rating: 5,
      buttonText: "Check Availability",
    },
    {
      id: 11,
      name: "Shwe Kyun Hotel",
      slug: "shwe-kyun-hotel",
      location: "Bagan",
      description:
        "Staying at The Savoy London was like stepping into a world of refined elegance. The room was a perfect blend of classic British charm and modern luxury, with a marble bathroom and plush furnishings. The personalized service was exceptional; the staff remembered my name and preferences throughout my stay.",
      images: [
        "/src/assets/hotel-assets/11.Shwe Kyun Hotel/Hotels_Shwe Kyun_1.png",
        "/src/assets/hotel-assets/11.Shwe Kyun Hotel/Hotels_Shwe Kyun_2.png",
        "/src/assets/hotel-assets/11.Shwe Kyun Hotel/Hotels_Shwe Kyun_3.png",
        "/src/assets/hotel-assets/11.Shwe Kyun Hotel/Hotels_Shwe Kyun_4.png",
      ],
      reviews: 4321,
      rating: 3,
      buttonText: "Check Availability",
    },
    {
      id: 12,
      name: "Tharabar Gate Hotel",
      slug: "tharabar-gate-hotel",
      location: "Bagan",
      description:
        "The newly restored Raffles Singapore is a blend of history and modern luxury. My suite was spacious and elegant, with beautiful colonial decor and cutting-edge technology. The legendary Long Bar, where the Myanmar Sling was invented, lived up to its reputation.",
      images: [
        "/src/assets/hotel-assets/12.Tharabar Gate Hotel/Hotels_Tharabar_1.png",
        "/src/assets/hotel-assets/12.Tharabar Gate Hotel/Hotels_Tharabar_2.png",
        "/src/assets/hotel-assets/12.Tharabar Gate Hotel/Hotels_Tharabar_3.png",
        "/src/assets/hotel-assets/12.Tharabar Gate Hotel/Hotels_Tharabar_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 13,
      name: "Pan Pacific Yangon",
      slug: "pan-pacific-yangon",
      location: "Yangon",
      description:
        "The afternoon tea at the Palm Court was an unforgettable experience, steeped in tradition and elegance. The concierge service was top-notch, helping me with everything from reservations to local recommendations. The Plaza isn’t just a hotel—it’s an experience that embodies the spirit of Mandalay luxury.",
      images: [
        "/src/assets/hotel-assets/13.Pan Pacific Hotel/Hotels_Pan Pacific_1.png",
        "/src/assets/hotel-assets/13.Pan Pacific Hotel/Hotels_Pan Pacific_2.png",
        "/src/assets/hotel-assets/13.Pan Pacific Hotel/Hotels_Pan Pacific_3.png",
        "/src/assets/hotel-assets/13.Pan Pacific Hotel/Hotels_Pan Pacific_4.png",
      ],
      reviews: 4321,
      rating: 5,
      buttonText: "Check Availability",
    },
    {
      id: 14,
      name: "Ruper Mandalar Resort",
      slug: "ruper-mandalar-resort",
      location: "Mandalay",
      description:
        "The breakfast buffet was extensive, with something for everyone, including local Burmese specialties. The hotel staff were always smiling and eager to help. While it wasn’t as luxurious as a 5-star resort, it was warm, welcoming, and excellent value for money. Highly recommended for families!",
      images: [
        "/src/assets/hotel-assets/14.Ruper Mandalar Resort/Hotels_Ruper Mandalar_1.png",
        "/src/assets/hotel-assets/14.Ruper Mandalar Resort/Hotels_Ruper Mandalar_2.png",
        "/src/assets/hotel-assets/14.Ruper Mandalar Resort/Hotels_Ruper Mandalar_3.png",
        "/src/assets/hotel-assets/14.Ruper Mandalar Resort/Hotels_Ruper Mandalar_4.png",
      ],
      reviews: 4321,
      rating: 2,
      buttonText: "Check Availability",
    },
    {
      id: 15,
      name: "Eastern Paradise Hotel",
      slug: "eastern-paradise-hotel",
      location: "Taunggyi",
      description:
        "My suite was impeccably designed, featuring floor-to-ceiling windows with panoramic views of Taunggyi. The rooftop pool and lounge were the perfect spots to unwind and take in the sunset. The hotel is cozy yet modern, with friendly staff and excellent amenities, making it the perfect place to relax and indulging in the local market scene.",
      images: [
        "/src/assets/hotel-assets/15.Eastern Paradise Hotel/Hotels_Eastern Paradise_1.png",
        "/src/assets/hotel-assets/15.Eastern Paradise Hotel/Hotels_Eastern Paradise_2.png",
        "/src/assets/hotel-assets/15.Eastern Paradise Hotel/Hotels_Eastern Paradise_3.png",
        "/src/assets/hotel-assets/15.Eastern Paradise Hotel/Hotels_Eastern Paradise_4.png",
      ],
      reviews: 4321,
      rating: 5,
      buttonText: "Check Availability",
    },
    {
      id: 16,
      name: "Amazing Bagan Resort",
      slug: "amazing-bagan-resort",
      location: "Bagan",
      description:
        "While it’s not directly on the beach, the staff arranged private beach access with a guided walk. The level of personalized service was outstanding. The resort's eco-conscious design and the peaceful atmosphere made it an unforgettable stay for those seeking beachside luxury with a twist.",
      images: [
        "/src/assets/hotel-assets/16.Amazing Bagan Resort/Hotels_Amazing Bagan_1.png",
        "/src/assets/hotel-assets/16.Amazing Bagan Resort/Hotels_Amazing Bagan_2.png",
        "/src/assets/hotel-assets/16.Amazing Bagan Resort/Hotels_Amazing Bagan_3.png",
        "/src/assets/hotel-assets/16.Amazing Bagan Resort/Hotels_Amazing Bagan_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 17,
      name: "Belmond Governor’s Residence",
      slug: "belmond-governors-residence",
      location: "Yangon",
      description:
        "My room was lavishly decorated, featuring traditional Burmese motifs, a private terrace, and a semi-private pool. The dining experience was equally regal, with candlelit dinners overlooking the lake and authentic Burmese cuisine that was a treat for the senses.",
      images: [
        "/src/assets/hotel-assets/17.Belmond Hotel/Hotels_Belmond Governor's_1.png",
        "/src/assets/hotel-assets/17.Belmond Hotel/Hotels_Belmond Governor's_2.png",
        "/src/assets/hotel-assets/17.Belmond Hotel/Hotels_Belmond Governor's_3.png",
        "/src/assets/hotel-assets/17.Belmond Hotel/Hotels_Belmond Governor's_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 18,
      name: "Mercure Mandalay Hill",
      slug: "mercure-mandalay-hill",
      location: "Mandalay",
      description:
        "The staff were friendly and multilingual, which made check-in a breeze. Breakfast was delicious, with Mohinga and a variety of hot options. The hotel also had a small fitness center, which was a nice bonus. Great for travelers looking for quality without breaking the bank.",
      images: [
        "//src/assets/hotel-assets/18.Mercure Mandalay Hotel/Hotels_Mercure_1.png",
        "/src/assets/hotel-assets/18.Mercure Mandalay Hotel/Hotels_Mercure_2.png",
        "/src/assets/hotel-assets/18.Mercure Mandalay Hotel/Hotels_Mercure_3.png",
        "/src/assets/hotel-assets/18.Mercure Mandalay Hotel/Hotels_Mercure_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 19,
      name: "Royal Taunggyi Hotel",
      slug: "royal-taunggyi-hotel",
      location: "Taunggyi",
      description:
        "My suite was luxurious, with traditional Indian decor, a private balcony, and a marble bathroom with a soaking tub. The service was exceptional, with staff treating every guest like royalty. My room had a large balcony where I could take in the majestic landscape every morning.",
      images: [
        "/src/assets/hotel-assets/19.Royal Taungyi Hotel/Hotels_Royal Taungyi_1.png",
        "/src/assets/hotel-assets/19.Royal Taungyi Hotel/Hotels_Royal Taungyi_2.png",
        "/src/assets/hotel-assets/19.Royal Taungyi Hotel/Hotels_Royal Taungyi_3.png",
        "/src/assets/hotel-assets/19.Royal Taungyi Hotel/Hotels_Royal Taungyi_4.png",
      ],
      reviews: 2321,
      rating: 2,
      buttonText: "Check Availability",
    },
    {
      id: 20,
      name: "The Hotel Bagan Umbra",
      slug: "the-hotel-bagan-umbra",
      location: "Bagan",
      description:
        "The service was exceptional, with staff anticipating my needs before I even asked. The hotel’s location made it easy to explore the city’s attractions and vibrant markets. Staying here is not just a stay—it’s an experience steeped in history and elegance.",
      images: [
        "/src/assets/hotel-assets/20.The Bagan Hotel/Hotels_The Hotel Bagan_1.png",
        "/src/assets/hotel-assets/20.The Bagan Hotel/Hotels_The Hotel Bagan_2.png",
        "/src/assets/hotel-assets/20.The Bagan Hotel/Hotels_The Hotel Bagan_3.png",
        "/src/assets/hotel-assets/20.The Bagan Hotel/Hotels_The Hotel Bagan_4.png",
      ],
      reviews: 3321,
      rating: 3,
      buttonText: "Check Availability",
    },
    {
      id: 21,
      name: "Hilton Mandalay",
      slug: "hilton-mandalay",
      location: "Mandalay",
      description:
        "Staying at the Aureum Palace Hotel & Resort Bagan was a treat. The boutique-style rooms were cozy and full of character, blending modern decor with nods to the city’s history. The bed was incredibly comfortable, and the complimentary snacks in the minibar were a nice touch.",
      images: [
        "/src/assets/hotel-assets/21.Hilton Mandalay Hotel/Hotels_Hilton_1.png",
        "/src/assets/hotel-assets/21.Hilton Mandalay Hotel/Hotels_Hilton_2.png",
        "/src/assets/hotel-assets/21.Hilton Mandalay Hotel/Hotels_Hilton_3.png",
        "/src/assets/hotel-assets/21.Hilton Mandalay Hotel/Hotels_Hilton_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 22,
      name: "Aythaya Vineyard Resort",
      slug: "aythaya-vineyard-resort",
      location: "Mandalay",
      description:
        "The Kanbawza Hinthar is the epitome of opulence. From the grand marble lobby to the gold-plated coffee served at the café, every detail screams luxury. My room was lavishly appointed with Europian-inspired decor, a massive bed, and a balcony overlooking the sea.",
      images: [
        "/src/assets/hotel-assets/22.Aythaya Vineyard Resort/Hotels_Aythaya Vineyard_!.png",
        "/src/assets/hotel-assets/22.Aythaya Vineyard Resort/Hotels_Aythaya Vineyard_2.png",
        "/src/assets/hotel-assets/22.Aythaya Vineyard Resort/Hotels_Aythaya Vineyard_3.png",
        "/src/assets/hotel-assets/22.Aythaya Vineyard Resort/Hotels_Aythaya Vineyard_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 23,
      name: "Sule Shangri-La, Yangon",
      slug: "sule-shangri-la-yangon",
      location: "Yangon",
      description:
        "I stayed at the Mingalar Mandalay Hotel for a business trip and was thoroughly impressed. The location was excellent, right in the heart of the city and walking distance to major attractions. The room was modern, clean, and well-equipped, with a spacious desk and a very comfortable bed.",
      images: [
        "/src/assets/hotel-assets/23.Sule Shangri-La Hotel/Hotels_Shangri-La_1.png",
        "/src/assets/hotel-assets/23.Sule Shangri-La Hotel/Hotels_Shangri-La_2.png",
        "/src/assets/hotel-assets/23.Sule Shangri-La Hotel/Hotels_Shangri-La_3.png",
        "/src/assets/hotel-assets/23.Sule Shangri-La Hotel/Hotels_Shangri-La_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
    {
      id: 24,
      name: "Bagan Thandel Hotel",
      slug: "bagan-thandel-hotel",
      location: "Bagan",
      description:
        "Claridge's in London is the pinnacle of traditional Burmese luxury. The room was elegant and refined, with plush furnishings and a marble bathroom. Afternoon tea in the grand lobby was a highlight, featuring the finest teas and an array of delicate pastries.",
      images: [
        "/src/assets/hotel-assets/24.Bagan Thandel Hotel/Hotels_Bagan Thande_1.png",
        "/src/assets/hotel-assets/24.Bagan Thandel Hotel/Hotels_Bagan Thande_2.png",
        "/src/assets/hotel-assets/24.Bagan Thandel Hotel/Hotels_Bagan Thande_3.png",
        "/src/assets/hotel-assets/24.Bagan Thandel Hotel/Hotels_Bagan Thande_4.png",
      ],
      reviews: 4321,
      rating: 4,
      buttonText: "Check Availability",
    },
  ],

  setHotels: (hotels) => (this.hotels = hotels),
}));

export default useHotelStore;
